resources:
  repositories:
  - repository: secondaryRepo      
    type: Git
    name: p1
    source: p1

jobs:
- job: download_specific_artifact1
  displayName: download specific artifact1
  pool:
    name: Default
  steps:
    - task: PublishBuildArtifacts@1
      displayName: ArtifactInGHYaml
      inputs:
        pathToPublish: 'README.md'
        artifactName: ArtifactInGHYaml
