resources:
  repositories:
  - repository: secondaryRepo      
    type: Git
    name: p1

jobs:
- job: download_specific_artifact1
  displayName: download specific artifact1
  pool:
    name: Default

