resources:
  Repositories:
  - repository: secondaryRepo      
    type: Git

jobs:
- job: download_specific_artifact1
  displayName: download specific artifact1
  pool:
    name: Default
  steps:
    - checkout: secondaryRepo
