resources:
  pipelines:
  - pipeline: MyPipeline1
    project: p1
    source: p1-CI
  - pipeline: MyPipeline2
    project: p1
    source: p1-CI2

jobs:
- job: download_specific_artifact1
  displayName: download specific artifact1
  pool:
    name: Default
  steps:
    - download: MyPipeline1

- job: download_specific_artifact2
  displayName: download specific artifact2
  dependsOn: download_specific_artifact1
  pool:
    name: Default
  steps:
    - download: MyPipeline2
